### PR TITLE
Bump up dependency versions

### PR DESCRIPTION
**Pull request by pvik**
Bumping up dependency versions
and also adding a simple example directly in the README

### CODE REVIEW

**Comment by pvik** [comment]
@siscia I noticed your comments on other open issues looking for a maintainer. 
Please let me know if you want me to take over maintenance of this package. 
I will be happy to do so!

**Comment by siscia** [comment]
Hi @pvik ,

was necessary to bump up the dependencies?

I can guess the older dependencies we use the better. Especially if we don't cross the major releases.
I noticed that the dependencies for `org.postgresql/postgresql` completely changed though.

Also I believe, that we should upgrade also the version of the library to something like `0.0.5` or even `0.1.0`. I guess it depends on the why we bump up the dependencies...

I will be more than happy to leave the maintainership of this project to you, so consider the above comments just like suggestions, you are the one that are going to merge them ;)

I don't know what is necessary to do on the clojars platform though...

Cheers,
Simone

**Comment by siscia** [comment]
I make you a collaborator of the project, but maybe I should transfer the ownership completely.

I believe the cleanest way could be that I make you a collaborator, we work together to set everything on clojars (do we want to keep the `siscia` namespace, change it to the `pvik` namespace or even change it completely to something like an organization) and then I transfer the ownership of the project to whoever necessary.

I never did this kind of changes though...

**Comment by pvik** [comment]
I bumped up the versions because it was pulling in older versions of the libraries already in my classpath!

I think it might make sense to have these dependencies as `:managed-dependencies` since the base project using this package should be including them anyways :)

I'll let you decide how to deal with the ownership! I am ok if you want to transfer it to me or if you want me on as a collaborator.

**Comment by siscia** [comment]
I am definitely ok with transfering the git repo to you!

My real concern is about the clojars project, it should use my name as namespace and I am not sure it is a good idea.

Did you already publish on clojars under your namespace?

**Comment by pvik** [comment]
I think it might be easier to continue maintaining this on my fork and have a "Notice" message on the README.md file in this repo pointing to the new one?  

I could also update the project.clj under my fork to push to clojars under my namespace?

I think that would be the simplest solution.

**Comment by siscia** [comment]
That sounds great!

You have all the rights in this repo, so please do whatever you believe is the most appropriate.

Cheers

**Pull request merged**
